[package]
name = "yet-another-disk-mapper"
version = "0.1.0"
edition = "2021"

[dependencies]
rmp-serde = "1.3.0"
serde = "1.0.219"

[profile.custom-opt]
inherits = "release"
opt-level = 3
lto = true
codegen-units = 1